### ISSUE TITLE
FR: Config option to disable per environment

### ISSUE THREAD

**Issue by lindseydiloreto** [nystudio107/instantanalytics#1]
Feature request...

Can we have an environment-aware config option for "run analytics"? We'd like to keep the analytics disabled on the staging server, where we're not running in `devMode`.

The way you did it in SEOmatic is perfect!

https://github.com/nystudio107/seomatic/blob/master/config.php#L58

**Comment by khalwat** [comment]
Implemented in `develop`:

https://github.com/nystudio107/instantanalytics/tree/develop
