### ISSUE TITLE
Error on product detail view

### ISSUE THREAD

**Issue by klick** [nystudio107/instantanalytics#15]
Hi.

With the latest update my product detail view is breaking with an error:

`Craft\Commerce_VariantModel and its behaviors do not have a method or closure named "getType".`

I’m trying to add a view like so:

`{% do instantAnalytics.addCommerceProductDetailView(variantActive) %}`

where `variantActive` is an object.

But also this does not work: 

`{% do instantAnalytics.addCommerceProductDetailView(product.defaultVariant.id) %}`

What changed? 
What exactly is supposed to be passed on here?

Best,
M

**Comment by khalwat** [comment]
Hmmm, I will have a look at the diff

**Comment by klick** [comment]
Thank you.

**Comment by khalwat** [comment]
Looks like a regression when I fixed things for Digital Product support. Try the build in the `develop` branch:

https://github.com/nystudio107/instantanalytics/tree/develop

...and let me know how that goes?

**Comment by khalwat** [comment]
@klick @Tam lmk if you have issues with the `develop` build in your environment.

**Comment by klick** [comment]
That seems to work better.

**Comment by Tam** [comment]
@khalwat No issues, that's working fine for me

**Comment by khalwat** [comment]
Great, thanks, I will release today.
