### ISSUE TITLE
UTM Parameter not working with Instant Analytics

### ISSUE THREAD

**Issue by hongc-cc** [nystudio107/instantanalytics#16]
Edited:
TL;DR: Pageview with UTM parameter not working.

We used UTM parameters to mark all external Pageviews from Newsletter, instagram..etc.

Pageview URL with UTM Parameters (e.g. utm_campaign, utm_source, utm_medium) will get those UTM parameters stripped. In GA, these view's source/medium will become "yourdomain.com / referral", and the URL get recorder would have the UTM parameters stripped. 

I am not sure if this is standard behaviour of Google Analytics Measurement Protocol, and if we should write a twig snippet to convert the UTM_campaign into `instantAnalytics.setCampaignName` .

**Comment by khalwat** [comment]
Ah, so you're expecting that it would look at the query string, and automatically decode those UTM parameters?

Currently it does not do that, and you'd have to do it manually as you mentioned, but that's an interesting idea for a FR.

**Comment by khalwat** [comment]
@idolab ?

**Comment by khalwat** [comment]
I added support for this in 1.1.12:

https://github.com/nystudio107/instantanalytics/releases/tag/1.1.12

...which I _think_ is what you wanted @idolab

**Comment by hongc-cc** [comment]
argh.. i didn't publish my prevous comment, sorry for that @khalwat 
Actually i wrote a little script to fix that, but i am very happy that you take auto-parsing into the plugin! cool!
