### ISSUE TITLE
eventTrack doesn't redirect if no filename

### ISSUE THREAD

**Issue by phaetons** [nystudio107/instantanalytics#3]
I tried to eventTrack a link with an url. 
The adress _/instantanalytics/eventTrack?url=http%253A%252F%252Fwww.demo.de&eventCategory=MyCategroy%2BTrackingUrl&eventAction=Click%2BLogo&eventLabel=Ad-Name&eventValue=someImpressions_ is called but didn't redirect to the given url.

It seems that the route is not working properly. I changed

`'instantanalytics/eventTrack/(?P<filename>[-\w\.*]+)'       => array('action' => 'instantAnalytics/trackEventUrl'),`

to 

`'instantanalytics/eventTrack(/(?P<filename>[-\w\.*]+))?'       => array('action' => 'instantAnalytics/trackEventUrl'),`

so the trailing slash ist optional.

Beste regards
Stephan

**Comment by khalwat** [comment]
Ah, good call @phaetons thank you.  I will roll that in.
