### ISSUE TITLE
FR: Make Commerce Product Category Field a twig field

### ISSUE THREAD

**Issue by hongc-cc** [nystudio107/instantanalytics#4]
Most people use category to categorize their products. So maybe allow user to twig to get the values. (e.g. {{ product.category.first() }})

p.s. this plugin is cool.

**Comment by khalwat** [comment]
Agreed, I plan to add that in

**Comment by oyvindostmo** [comment]
Hi, I just ran into the same. We use category relations both for Product Category and Product Brand. Would be awesome to have this supported. We have a category structure with for example "Clothing > Mens > Jackets" and "Clothing > Womens > Jackets" so sending in "Jackets" wouldn't be unique. Maybe if we had the twig option we could loop through the category relations and send in the full "Clothing > Mens > Jackets". Or maybe the slug that in this case would be "mens-jackets" and "womens-jackets". We launch today - feeling inspired to do some magic? :)

**Comment by khalwat** [comment]
This has been implemented by @Tam and is available in the `develop` branch currently:

https://github.com/nystudio107/instantanalytics/tree/develop
