### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by oyvindostmo** [nystudio107/instantanalytics#6]
Hi,
is hostname supposed to be sent with the analytics tracking? Right now it all comes in as "not set". Our analytics partner needs this to filter out all traffic from other places than the website domain.

**Comment by khalwat** [comment]
You can easily add this in via Twig; do you think it's something that should be set by default?

**Comment by khalwat** [comment]
I checked in a fix to `develop` that sets the DocumentHostName by default:

https://github.com/nystudio107/instantanalytics/tree/develop

**Comment by khalwat** [comment]
This is fixed in 1.1.4 (just released)
