### ISSUE TITLE
php warnings

### ISSUE THREAD

**Issue by nealzie** [nystudio107/instantanalytics#9]
Hi!

When activating the plugin I get 500 server errors on my site. When switching to dev mode, I get this:

PHP warning

curl_init() has been disabled for security reasons

blabla/root/werkenbij/craft/plugins/instantanalytics/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(56)

Troubleshooting myself now but thought I'd report it in case.

**Comment by khalwat** [comment]
What version of PHP is on your server? Is this in local dev, and if so, what are you using for it?

It sounds like some kind of an issue with your server/PHP setup

**Comment by nealzie** [comment]
Local dev seems to work fine - php 5.6.10.
Staging gives this error which is Apache 2.4.23 - php 5.6.27

**Comment by khalwat** [comment]
How was staging provisioned? The error you're seeing is coming from Guzzle, a widely used PHP package that Instant Analytics uses. I'm suspecting something is amiss with your server provisioning.

**Comment by khalwat** [comment]
Maybe this will help you: https://tipstricks.itmatrix.eu/warning-curl_exec-has-been-disabled-for-security-reasons/
